### ISSUE TITLE
add 2 new db pages

### ISSUE THREAD

**Issue by Lfickling** [SW-Dev-Methods-Team-2/Project1#11]
1 - customer information (see user stories for reqs) including customer id (should be randomly generated for internal use) email, shipping address, first name, last name, user id. for user id maybe use hashcode()?
2- order history (including snapshot of items thing? derek please clarify) - order date, associated user id, order # (ascending in order received?), quantity dollar amount, snapshot of ordered items?

**Comment by DARhine** [comment]
Userdata table:  email shipping first/last name userID 
Order table, match inventory and add user ID....

**Comment by DARhine** [comment]
2 new tables created for user_data and sales_orders
